'use client';
import {useState} from 'react'; import {categories as initialCategories,categoryCriteria as initialCriteria,Criterion} from '@/lib/data';
export default function Admin(){
 const [categories,setCategories]=useState(initialCategories); const [criteria,setCriteria]=useState(initialCriteria); const [selected,setSelected]=useState(initialCategories[0].name); const [name,setName]=useState(''); const [type,setType]=useState<Criterion['type']>('select'); const [newCategory,setNewCategory]=useState('');
 const addCategory=()=>{const n=newCategory.trim();if(!n||categories.some(c=>c.name===n))return;setCategories([...categories,{name:n,desc:'Yeni ürün kategorisi',icon:'▣'}]);setCriteria(v=>({...v,[n]:[]}));setSelected(n);setNewCategory('')};
 const add=()=>{if(!name.trim())return;const key=name.toLowerCase().replace(/[^a-z0-9]+/g,'_');setCriteria(v=>({...v,[selected]:[...(v[selected]||[]),{key:key,label:name,type:type,values:type==='boolean'?['Var','Yok']:[]}]}));setName('')};
 return <main className="container" style={{paddingTop:35}}><h1>Admin Paneli</h1>
 <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:15,marginTop:20}}>{[['Toplam Firma','438'],['Aktif Abone','327'],['Toplam Ürün','12.845'],['Teklif Talepleri','2.384']].map(x=><div className="card" style={{padding:22}} key={x[0]}><div style={{color:'var(--muted)'}}>{x[0]}</div><div style={{fontSize:28,fontWeight:800,marginTop:8}}>{x[1]}</div></div>)}</div>
 <div className="card" style={{padding:22,marginTop:25}}><h2>Ürün Kategorileri</h2><p style={{color:'var(--muted)'}}>Admin tüm ürün kategorilerini oluşturur ve her kategoriye ayrı teknik kriter seti tanımlar.</p><div style={{display:'flex',gap:10}}><input value={newCategory} onChange={e=>setNewCategory(e.target.value)} placeholder="Yeni kategori adı" style={{flex:1,padding:11}}/><button onClick={addCategory} style={{padding:'11px 18px'}}>Kategori Ekle</button></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:15}}>{categories.map(c=><button key={c.name} onClick={()=>setSelected(c.name)} style={{padding:'9px 12px',fontWeight:selected===c.name?800:400}}>{c.icon} {c.name}</button>)}</div></div>
 <div className="card" style={{padding:22,marginTop:25}}><h2>{selected} — Teknik Özellikler</h2><p style={{color:'var(--muted)'}}>Bu kriterler filtreleme, ürün girişi ve ileride teknik karşılaştırma/AI eşleştirme için kullanılacaktır.</p><div style={{display:'flex',gap:10,margin:'18px 0'}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Yeni teknik özellik adı" style={{flex:1,padding:11}}/><select value={type} onChange={e=>setType(e.target.value as Criterion['type'])} style={{padding:11}}><option value="select">Seçim</option><option value="number">Sayısal</option><option value="boolean">Evet/Hayır</option><option value="multiselect">Çoklu seçim</option></select><button onClick={add} style={{padding:'11px 18px'}}>Özellik Ekle</button></div><div style={{display:'grid',gridTemplateColumns:'1fr 150px',gap:8}}>{(criteria[selected]||[]).map(c=><div key={c.key} style={{display:'contents'}}><div style={{padding:10,borderBottom:'1px solid #edf0f5'}}>{c.label}</div><div style={{padding:10,borderBottom:'1px solid #edf0f5',color:'var(--muted)'}}>{c.type}</div></div>)}</div></div></main>}
